/*
 *  Settings.h
 *  UDON
 *
 *  Created by giginet on 11/03/05.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */

#define MYCHARAWIDTH 68
#define MYCHARAHEIGHT 60
#define MYCHARAINITIALX 50
#define MYCHARAINITIALY 150
#define MYCHARAINITIALSPEED 8
#define MYCHARAMOGMAX 5
#define MYCHARAINITIALHP 1
#define MOGAREARADIUS 230
#define MYCHARASPEEDDOWN 0.7

#define PREFECTUREWIDTH 88
#define PREFECTUREHEIGHT 90

#define PREFECTURECOUNT 47

#define BACKGROUNDWIDTH 853
#define INITIALPOPRATE 100
#define MINPOPRATE 10

#define MAXENEMY 15